### PR TITLE
add task watch in Cakefile

### PR DESCRIPTION
**Pull request by rmetzler**
I added a task in Cakefile to watch the source .coffee files and rebuild whenever these files are changing.

This should increase development turnaround.

### CODE REVIEW

**Comment by scien** [comment]
how about adding -l to show potential syntax error?

```
run 'coffee -w -l -o lib -c src/*.coffee'
```

```
00:00:24 - compiled src/client.coffee
00:00:33 - compiled src/zappa.coffee
00:00:38 - compiled src/zappa.coffee
In src/zappa.coffee, Parse error on line 565: Unexpected '='
00:00:45 - compiled src/zappa.coffee
```

**Comment by shimaore** [comment]
I must be missing the use case, sorry if I'm being thick here. I'm trying to understand why this would go into zappa's `Cakefile`.

Generally I create a separate project for each of my zappa applications, with a dedicated `package.json`. In that case a command like this would go into that project's `package.json` or something similar.

Do you guys mean that you are developing applications from within the zappa source tree? Or is this really to help with `zappa.coffee` development? (I tend to rely on `cake test` in that later case.)

**Comment by scien** [comment]
this would be for zappa.coffee development.  but yeah, "cake test" does a build. so i guess there's not much use in this aside from learning about syntax errors sooner while working on zappa.coffee.  i doubt i'd use it

**Comment by Radagaisus** [comment]
+1 with `-l`. This will make zappa development a little bit easier :)

**Comment by shimaore** [comment]
Moved to zappajs-template

**Pull request closed without merging**
