### PR TITLE
@ack for socket.io acknowledgements 

### PR DESCRIPTION
**Pull request by Radagaisus**
There's no way, as far as I can tell, to acknowledge messages in socket.io.

This fix adds @ack to the scope of @on.

### CODE REVIEW

**Comment by shimaore** [comment]
Wouldn't this be part of the protocol you implement on top of socket.io, for example by using `@emit ack: {...}` and `@on ack: -> ...` ?

**Comment by Radagaisus** [comment]
No, acknowledgements are only sent back when you receive a message, and only to the sender.

``` coffee
@on get_stuff: ->
        @ack stuff: 'here it is'
```

**Comment by Radagaisus** [comment]
from the docs:

Sometimes, you might want to get a callback when the client confirmed the message reception.

To do this, simply pass a function as the last parameter of `.send` or `.emit`. What's more, when you use `.emit`, the acknowledgement is done by you, which means you can also pass data along:

``` javascript
var io = require('socket.io').listen(80);

io.sockets.on('connection', function (socket) {
  socket.on('ferret', function (name, fn) {
    fn('woot');
  });
});
```

**Comment by shimaore** [comment]
OK, got it. `@ack` is a reference to socket.io's [`ack()`](https://github.com/LearnBoost/socket.io/blob/master/lib/namespace.js#L271).
Could you draft some documentation (which could be inserted in the `Sockets Handlers Scope` section of `docs/0.3-gumbo/reference.md` for example) and maybe a complete usage example (client and server sides in a single zappa file)?

**Comment by Radagaisus** [comment]
Sure. Btw, all the socket.io tests are already failing, so I didn't add any tests.

**Comment by shimaore** [comment]
With the move to socket.io 0.9.x the tests work again, so I added a test for this.

**Comment by Radagaisus** [comment]
Awesome! When is everything going to be published in npm? I'm deploying with my own repository right now.

**Comment by scien** [comment]
what's the reason for using @data and @ack?

It looks like socket.io let's you just pass in any list of arguments.  example from their website…

```
<script>
  var socket = io.connect(); // TIP: .connect with no args does auto-discovery
  socket.on('connect', function () { // TIP: you can avoid listening on `connect` and listen on events directly too!
    socket.emit('ferret', 'tobi', function (data) {
      console.log(data); // data will be 'woot'
    });
  });
</script>
```

```
var io = require('socket.io').listen(80);

io.sockets.on('connection', function (socket) {
  socket.on('ferret', function (name, fn) {
    fn('woot');
  });
});

```

an example zappa app might look like…

```
require('./zappajs') ->

  @get '/': ->
    @render index: {layout: no}

  @on foo: (a, b, fn) ->
    console.log a
    console.log b
    console.log fn
    fn 'x', 'y'

  @client '/index.js': ->
    @connect()
    $ =>
      @emit 'foo', 'a', 'b', (x, y) ->
        console.log "#{x} #{y}"

  @view index: ->
    doctype 5
    html ->
      head ->
        script src: '/zappa/Zappa-simple.js'
        script src: '/index.js'
```

this works with a simple change to zappa.coffee by applying the arguments to the handler in the socket handlers scope

```
h.apply ctx, arguments
```

Could this have unwanted consequences? Is there a reason for not allowing this?

**Comment by shimaore** [comment]
@scien 
Your first example shows a `ack` function:

```
socket.emit('ferret', 'tobi', function (data) {
  console.log(data); // data will be 'woot'
});
```

In that case you'd write:

```
@on 'ferret', ->
  console.log @data  #  "tobi"
  @ack 'woot'
```

on the server.

In your second example you would write

```
@on foo: ->
  console.log @data.a
  console.log @data.b
  @ack 'x', 'y'
```

and then

```
a = 'a'
b = 'b'
@emit 'foo', {a,b}, (x, y) ->
   console.log "#{x} #{y}"
```

In terms of API Zappa has always used `@data` to mean "the first argument of `emit`", assuming it would be an object (array...) if it was a complex structure.

The "passing the arguments along" way of doing things isn't Zappa-esque (we could pass `(req,res,next)`), but you can get your cake and eat it, if you don't care for helper functions:

```
@io.on 'foo', (a, b, fn) ->
```

**Comment by scien** [comment]
Yeah. I get how @data and @ack are being used. I'm just curious as to why that structure was chosen (or why not to share the same syntax with socket.io).  Is passing all arguments as an object like @data common in other libraries/frameworks?

Is it just me, or does using 

```
socket.on('ferret', function (name, fn) {
```

just feel better?  A few reasons for that argument...
1. You know what parameters the server is expecting instead of having to write a bunch of documentation above each function letting people know "this function should get a parameter in @data.name)
2. more succinct function calls @emit 'say', 'hello', 'world' vs @emit say: {hello: 'hello', world: 'world'}
3. the socket.io ways feels more like calling any other function, while the zappa way feels like i'm using $.ajax.
4. when using @ack in zappa i ended up almost always writing @ack a, b, c if @ack because the client might not always send a callback.  might be nice to make @ack an anonymous function that only calls the callback if it exists

reasons against
1. @emit say: {hello: 'hello', world: 'world'} makes it obvious 'say' is a function and {} are the params, where that's not as obvious in @emit 'say', 'hello', 'world' unless you're familiar with that syntax

Thoughts on any of this?

**Pull request closed without merging**
