### PR TITLE
Tests for @param

### PR DESCRIPTION
**Pull request by Radagaisus**
Sup,

1) I moved the build status to the top

2) Added tests for `@param` and changed the code for it (it didn't work). The docs should be adjusted a bit.

3) It's 2am here, so I'll continue next weekend =/

### CODE REVIEW

**Comment by shimaore** [comment]
I didn't do the two-arguments version because that would make `@param` the only one with that API in zappajs (`@get` etc. accept multiple arguments, but that's only in the case middleware is used).

**Comment by Radagaisus** [comment]
@shimaore you've merged all the changes in this issue, right? can we close it?

**Comment by Radagaisus** [comment]
@shimaore Oh man I hate github pull requests. Here's the tests for `@all`.

**Comment by shimaore** [comment]
Looks like you're testing `'/*'` rather than `@all` ? `@all` should be tested againt `get`, `put`, etc.

**Comment by shimaore** [comment]
maybe this should be moved to a new issue so that people don't get confused

**Comment by shimaore** [comment]
Actually the tests for `@all` should be in #40
I'm closing this one to avoid confusion

**Pull request closed without merging**
